services:
  movie-client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: movie-client
    image: congdinh2012/movie-client:latest
    ports:
      - "4200:80"
    volumes:
      - /app/node_modules
      - ../client:/app
    environment:
      ANG_APP_API_URL: ${ANG_APP_API_URL}
      NODE_ENV: production
    networks:
      - app_network

volumes:
  node_modules:
  app:

networks:
  app_network:
