services:
  ims-server:
    build:
      context: ../server
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        ANG_APP_API_URL: ${ANG_APP_API_URL}
        ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
        ANG_APP_URL: ${ANG_APP_URL}
    container_name: movie-server
    image: congdinh2012/movie-server:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      ANG_APP_API_URL: ${ANG_APP_API_URL}
      ANG_APP_URL: ${ANG_APP_URL}
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
